In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

# import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames[2:]:
#         test_df=pd.read_csv(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
test_df=pd.read_csv('../input/chaii-hindi-and-tamil-question-answering/test.csv')

In [3]:
test_df

,id,context,question,language
0,be799d365,एशियन पेंट्स लिमिटेड एक भारतीय बहुराष्ट्रीय कम...,एशियन पेंट्स कंपनी का मुख्यालय कहाँ स्थित है?,hindi
1,26f356026,स्वामी निगमानन्द परमहंस (18 अगस्त 1880 - 29 नव...,स्वामी निगमानन्द परमहंस के तन्त्र गुरु कौन थे?,hindi
2,57a56c43f,மனித மூளை மனித நரம்பு மண்டலத்தின் தலைமையானதும்...,மூளையின் மிகப்பெரிய பகுதி எது?,tamil
3,da062fdbb,अजातशत्रु (लगभग 493 ई. पू.[1]) मगध का एक प्रता...,सम्राट अजातशत्रु के पिता का क्या नाम था?,hindi
4,72fc0d5b5,एडोल्फ हिटलर (२० अप्रैल १८८९ - ३० अप्रैल १९४५)...,एडोल्फ हिटलर का जन्म कब हुआ था?,hindi
...,...,...,...,...
107,a5ddec2d9,ஜலாலுதீன் முகமது அக்பர் (உருது: جلال الدین محم...,இந்தியப் பேரரசர் அக்பர் எப்போது இறந்தார்?,tamil
108,e20a030f8,सोना या स्वर्ण (Gold) अत्यंत चमकदार मूल्यवान ध...,मैसूर में कोलार की खानों से कौन सी धातु प्राप्...,hindi
109,3c3513477,यूनान यूरोप महाद्वीप में स्थित देश है। यहां के...,यूनान की राजधानी क्या है?,hindi
110,934a3199c,"मिसिसिप्पी नदी (अंग्रेज़ी: Mississippi river, ...",मिसिसिप्पी नदी किस महाद्वीप में बहती है?,hindi
111,4f41fec88,कोशिका संवर्धन एक ऐसी जटिल प्रक्रिया है जिसके ...,कोशिका संवर्धन का आविष्कार किसने किया?,hindi

In [4]:
# !pip install transformers

In [5]:
from transformers import pipeline

2026-04-28 09:38:00.591479: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777369080.605814      11 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777369080.610139      11 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-04-28 09:38:00.628807: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

In [6]:
# # # question_answering = pipeline("question-answering",model='deepset/roberta-base-squad2',tokenizer='deepset/roberta-base-squad2', device=0)
# question_answering = pipeline("question-answering",model='abhishek/autonlp-hindi-question-answering-23865268',tokenizer='abhishek/autonlp-hindi-question-answering-23865268', device=0)
# question_answering

In [7]:
# import transformers as trf
# from transformers import pipeline, AutoModelForQuestionAnswering, AutoTokenizer,AutoConfig
# model = AutoModelForQuestionAnswering.from_pretrained("abhishek/autonlp-hindi-question-answering-23865268")
# tokenizer = AutoTokenizer.from_pretrained("abhishek/autonlp-hindi-question-answering-23865268")

In [8]:
# question_answering.tokenizer.save_pretrained('../input/model_')
# question_answering.model.save_pretrained('../input/model_')

In [9]:
# import transformers as trf
from transformers import pipeline, AutoModelForQuestionAnswering, AutoTokenizer,AutoConfig
model = AutoModelForQuestionAnswering.from_pretrained("../input/qa-data-hindi-tamil/autonlp-hindi-question-answering")
tokenizer = AutoTokenizer.from_pretrained("../input/qa-data-hindi-tamil/autonlp-hindi-question-answering")
config=AutoConfig.from_pretrained("../input/qa-data-hindi-tamil/autonlp-hindi-question-answering",)
model1=pipeline('question-answering', model=model, tokenizer=tokenizer,config=config,device=0)

HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '../input/qa-data-hindi-tamil/autonlp-hindi-question-answering'. Use `repo_type` argument if needed.

In [10]:

# # !pip install torch

# from transformers import AutoTokenizer, AutoModelForQuestionAnswering
# import torch

# tokenizer = AutoTokenizer.from_pretrained("../input/qa-data-hindi-tamil/autonlp-hindi-question-answering")
# model = AutoModelForQuestionAnswering.from_pretrained("../input/qa-data-hindi-tamil/autonlp-hindi-question-answering")

In [11]:


# text = r"""ज्वाला गुट्टा (जन्म: 7 सितंबर 1983; वर्धा, महाराष्ट्र) एक भारतीय बैडमिंटन खिलाडी हैं। 
#  प्रारंभिक जीवन 
# ज्वाला गुट्टा का जन्म 7 सितंबर 1983 को वर्धा, महाराष्ट्र में हुआ था। उनके पिता एम. क्रांति तेलुगु और मां येलन चीन से हैं। उनकी मां येलन गुट्टा पहली बार 1977 में अपने दादा जी के साथ भारत आई थीं। ज्वाला गुट्टा की प्रारंभिक पढ़ाई हैदराबाद से हुई और यहीं से उन्होंने बैडमिंटन खेलना भी शुरू किया। 
#  कॅरियर 
# 10 साल की उम्र से ही ज्वाला गुट्टा ने एस.एम. आरिफ से ट्रेनिंग लेना शुरू कर दिया था। एस.एम. आरिफ भारत के जाने माने खेल प्रशिक्षक हैं जिन्हें द्रोणाचार्य अवार्ड से सम्मानित किया गया है। पहली बार 13 साल की उम्र में उन्होंने मिनी नेशनल बैडमिंटन चैंपियनशिप जीती थी। साल 2000 में ज्वाला गुट्टा ने 17 साल की उम्र में जूनियर नेशनल बैडमिंटन चैंपियनशिप जीती। इसी साल उन्होंने श्रुति कुरियन के साथ डबल्स में जोड़ी बनाते हुए महिलाओं के डबल्स जूनियर नेशनल बैडमिंटन चैंपियनशिप और सीनियर नेशनल बैडमिंटन चैंपियनशिप में जीत हासिल की। श्रुति कुरियन के साथ उनकी जोड़ी काफी लंबे समय तक चली। 2002 से 2008 तक लगातार सात बार ज्वाला गुट्टा ने महिलाओं के नेशनल युगल प्रतियोगिता में जीत हासिल की।[2]
# महिला डबल्स के साथ-साथ ज्वाला गुट्टा ने मिश्रित डबल्स में भी सफलता हासिल की और भारत की डबल्स में सबसे बेहतरीन खिलाड़ी बनीं।[3] 2010 कॉमनवेल्थ गेम्स में भी ज्वाला गुट्टा ने अपने पार्टनर अश्विनी पोनप्पा के साथ भारत के लिए स्वर्ण पदक जीता। कॉमनवेल्थ गेम्स के बाद से एक बार फिर ज्वाला गुट्टा भारतीय बैडमिंटन में चर्चा का विषय बन गई हैं।[4][5]
# ग्लासगो में आयोजित कॉमनवेल्थ गेम्स, 2014 में ज्वाला गुट्टा ने स्वर्ण पदक हासिल किया।
#  व्यक्तिगत जीवन 
# मैदान पर बाएं हाथ से तेज-तर्रार शॉट लगाने वाली ज्वाला निजी जिंदगी में भी काफी तेज और चर्चाओं में छाई रहती हैं। ज्वाला ने 2005 में बैडमिंटन खिलाड़ी चेतन आनंद से शादी की थी, 29 जून 2011 को उन्होंने अपने पति पूर्व बैडमिंटन खिलाड़ी चेतन आनंद से तलाक लिया है। चेतन आनंद भी एक बेहतरीन भारतीय बैडमिंटन खिलाड़ी हैं।
#  फिल्मोग्राफी 
# Gunde Jaari Gallanthayyinde[6] 
# फुगली (2014)
#  उपलब्धियां 
# रिकॉर्ड 13 बार नेशनल बैडमिंटन चैंपियनशिप की विजेता। 
# भारत की सबसे बेहतरीन डबल्स प्लेयर। 
# साल 2011 में उन्हें “अर्जुन पुरस्कार” से सम्मानित किया गया। 
# राष्ट्रमंडल खेल, 2014 (ग्लासगो) में स्वर्ण पदक जीता। 
#  चित्र दीर्घा 


# वी दीजू और ज्वाला गुट्टा
# केबीसी के सेट पर सुशील कुमार, ज्वाला गुट्टा, लिएंडर पेस, श्रीसंत
# केबीसी के सेट पर सुशील कुमार, ज्वाला गुट्टा, लिएंडर पेस, श्रीसंत

#  सन्दर्भ 

#  बाहरी कड़ियाँ 





# श्रेणी:हिन्द की बेटियाँ
# श्रेणी:विकिपरियोजना हिन्द की बेटियाँ
# श्रेणी:भारत के खिलाड़ी
# श्रेणी:1983 में जन्मे लोग
# श्रेणी:जीवित लोग
# श्रेणी:भारतीय महिला बैडमिंटन खिलाड़ी
# श्रेणी:राष्ट्रमंडल खेलों के पदक प्राप्तकर्ता
# श्रेणी:महाराष्ट्र के लोग
# श्रेणी:बैडमिंटन खिलाड़ी"""

# questions = [
#     "'ज्वाला गुट्टा की माँ का नाम क्या है'"
# ]

# for question in questions:
#     inputs = tokenizer.encode_plus(question, text, add_special_tokens=False, return_tensors="pt" ,max_length=512)
#     input_ids = inputs["input_ids"].tolist()[0]

#     text_tokens = tokenizer.convert_ids_to_tokens(input_ids)
#     answer_start_scores, answer_end_scores = model(**inputs,return_dict=False)

#     answer_start = torch.argmax(
#         answer_start_scores
#     )  # Get the most likely beginning of answer with the argmax of the score
#     answer_end = torch.argmax(answer_end_scores) + 1  # Get the most likely end of answer with the argmax of the score

#     answer = tokenizer.convert_tokens_to_string(tokenizer.convert_ids_to_tokens(input_ids[answer_start:answer_end]))

#     print(f"Question: {question}")
#     print(f"Answer: {answer}\n")

In [12]:
# def predict_answer(question, context):
#     text=context
#     inputs = tokenizer.encode_plus(question, text, add_special_tokens=True, return_tensors="pt",max_length=512,truncation=False)
#     input_ids = inputs["input_ids"].tolist()[0]

#     text_tokens = tokenizer.convert_ids_to_tokens(input_ids)
#     answer_start_scores, answer_end_scores = model(**inputs,return_dict=False)

#     answer_start = torch.argmax(
#         answer_start_scores
#     )  # Get the most likely beginning of answer with the argmax of the score
#     answer_end = torch.argmax(answer_end_scores) + 1  # Get the most likely end of answer with the argmax of the score

#     answer = tokenizer.convert_tokens_to_string(tokenizer.convert_ids_to_tokens(input_ids[answer_start:answer_end]))
#     return answer

In [13]:
def predict_answer(question, context):
  result = model1(question=question, context=context)
  return result['answer']

In [14]:
import tqdm
context_lst = test_df['context'].to_list()
question_lst = test_df['question'].to_list()
print(len(question_lst))
predict_list= []
for i in tqdm.tqdm(range(len(question_lst))):
  ans = predict_answer(question_lst[i], context_lst[i],)
  predict_list.append(ans)

112

  0%|          | 0/112 [00:00<?, ?it/s]

NameError: name 'model1' is not defined

In [15]:
test_df['predicted_ans'] = predict_list
test_df

ValueError: Length of values (0) does not match length of index (112)

In [16]:
regList=[]
regList.append('^[0-9]+\.')
regList.append('^[0-9]\.')
regList.append('^[0-9][0-9]\.')
regList.append('^[0-9][0-9][0-9]\.')
regList.append('^[(][0-9]+[)]')
regList.append('^[0-9]+[)]')

for reg in regList:
           test_df['predicted_ans']=test_df['predicted_ans'].str.replace(reg,' ')


test_df['predicted_ans'] =  test_df['predicted_ans'].str.replace('(', '')
test_df['predicted_ans'] = test_df['predicted_ans'].str.replace(')', '')

KeyError: 'predicted_ans'

In [17]:
test_df

,id,context,question,language
0,be799d365,एशियन पेंट्स लिमिटेड एक भारतीय बहुराष्ट्रीय कम...,एशियन पेंट्स कंपनी का मुख्यालय कहाँ स्थित है?,hindi
1,26f356026,स्वामी निगमानन्द परमहंस (18 अगस्त 1880 - 29 नव...,स्वामी निगमानन्द परमहंस के तन्त्र गुरु कौन थे?,hindi
2,57a56c43f,மனித மூளை மனித நரம்பு மண்டலத்தின் தலைமையானதும்...,மூளையின் மிகப்பெரிய பகுதி எது?,tamil
3,da062fdbb,अजातशत्रु (लगभग 493 ई. पू.[1]) मगध का एक प्रता...,सम्राट अजातशत्रु के पिता का क्या नाम था?,hindi
4,72fc0d5b5,एडोल्फ हिटलर (२० अप्रैल १८८९ - ३० अप्रैल १९४५)...,एडोल्फ हिटलर का जन्म कब हुआ था?,hindi
...,...,...,...,...
107,a5ddec2d9,ஜலாலுதீன் முகமது அக்பர் (உருது: جلال الدین محم...,இந்தியப் பேரரசர் அக்பர் எப்போது இறந்தார்?,tamil
108,e20a030f8,सोना या स्वर्ण (Gold) अत्यंत चमकदार मूल्यवान ध...,मैसूर में कोलार की खानों से कौन सी धातु प्राप्...,hindi
109,3c3513477,यूनान यूरोप महाद्वीप में स्थित देश है। यहां के...,यूनान की राजधानी क्या है?,hindi
110,934a3199c,"मिसिसिप्पी नदी (अंग्रेज़ी: Mississippi river, ...",मिसिसिप्पी नदी किस महाद्वीप में बहती है?,hindi
111,4f41fec88,कोशिका संवर्धन एक ऐसी जटिल प्रक्रिया है जिसके ...,कोशिका संवर्धन का आविष्कार किसने किया?,hindi

In [18]:
final_test=pd.DataFrame()
final_test['id']=test_df['id']
final_test['PredictionString']=test_df['predicted_ans']

KeyError: 'predicted_ans'

In [19]:
final_test

            id
0    be799d365
1    26f356026
2    57a56c43f
3    da062fdbb
4    72fc0d5b5
..         ...
107  a5ddec2d9
108  e20a030f8
109  3c3513477
110  934a3199c
111  4f41fec88

[112 rows x 1 columns]

In [20]:
final_test.to_csv('submission.csv',index=False)